syntax on

" Only do this part when compiled with support for autocommands.
if has("autocmd")
    " Use filetype detection and file-based automatic indenting.
    filetype plugin indent on

    " Use actual tab chars in Makefiles.
    autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
endif

syntax enable

set tabstop=2         " The width of a TAB is set to 2.
set shiftwidth=2      " Indents will have a width of 2.
set softtabstop=2     " Sets the number of columns for a TAB.
set noexpandtab       " Expand TABs to spaces.
set number            " Put line numbers.
set spelllang=en_us   " Set spellcheck language.
set textwidth=80			" Set maximum line length.

let g:tex_flavor='latex'
