#!/bin/bash
### gshmake: Makes executable, bash-interpreted, PGP-encrypted scripts.
# gshmake accepts one script as an argument.
# Input scripts **should not** include a shebang (#!/bin/bash)

# Encrypt original script and output to a temporary file.
gpg2 --output /tmp/$1.asc --sign --armor --encrypt $1 

# Create GSH script and prepend commands to interpret encrypted portion.
cat > ${GSH}/$1 << EOF
#!/bin/bash

gpg2 --decrypt 2> /dev/null << EOF | bash -s \$@

EOF

# Import encrypted portion from the temporary file.
cat /tmp/$1.asc >> ${GSH}/$1

# Append EOF to close the PGP-encrypted portion.
printf "\nEOF" >> ${GSH}/$1

# Remove temporary file
rm /tmp/$1.asc

# Change GSH script owner to user and make executable.
chown $(whoami):$(whoami) ${GSH}/$1
chmod +x ${GSH}/$1
