#!/bin/bash

printf "Start numbering at:\n"
read START

printf "File extension:\n"
read FILETYPE

for FILE in *.$FILETYPE; do
  NEW=$(printf "%02d.$FILETYPE" "$START")
  mv -i -- "$FILE" "$NEW"
  let START=START+1
done
